name: Pylint

on: [push]

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v4
    - name: Install the project dependencies
      run: poetry install --with test
    - name: Analysing the code with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')
